import { Account } from './types';

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: '1',
    name: 'SoftBank Corp',
    shortName: 'SB',
    region: 'Japan',
    industry: 'Finance',
    healthScore: 42,
    grade: 'D',
    stage: 'Churn Risk',
    arr: 2100000,
    nrr: 82,
    renewalDays: 12,
    renewalDate: '2026-05-10',
    adoptionDepth: 24,
    lastActivity: '2h ago',
    csm: 'APAC Team',
    intervention: 'URGENT: Escalate to Senior CSM immediately. CTO departure = champion loss. Book emergency exec alignment call within 48hrs. Prepare Vendor Risk ROI report tailored to incoming replacement. Renewal in 12 days — do not let this lapse.',
    metrics: {
      loginFrequency: 15,
      featureAdoption: 45,
      supportVolume: 'Critical',
      csmEngagement: 60,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 3,
      riskAutomations: false,
    },
    news: [
      {
        id: 'n1',
        type: 'Executive Departure',
        title: 'Executive Departure',
        description: 'Primary Sponsor (CTO) has left the organization. Replacement unknown.',
        time: '2h ago',
        variant: 'error'
      },
      {
        id: 'n2',
        type: 'Expansion Opportunity',
        title: 'Expansion Signal',
        description: "Search volume for 'SIEM Integration' increased 400% in Tokyo office.",
        time: '1d ago',
        variant: 'primary'
      },
      {
        id: 'n2b',
        type: 'Renewal Alert',
        title: 'Renewal in 12 Days',
        description: 'Contract expires May 10. No renewal motion initiated yet.',
        time: '3d ago',
        variant: 'error'
      }
    ]
  },
  {
    id: '2',
    name: 'SingTel Group',
    shortName: 'SG',
    region: 'Singapore',
    industry: 'Telecommunications',
    healthScore: 92,
    grade: 'A',
    stage: 'Adopted',
    arr: 1240000,
    nrr: 112,
    renewalDays: 145,
    renewalDate: '2026-09-15',
    adoptionDepth: 88,
    lastActivity: '5h ago',
    csm: 'APAC Team',
    intervention: 'Schedule Q3 expansion review. Breach Risk module upsell — 3 active telco breach events in SG this quarter create strong business case. Nominate as MAS compliance case study.',
    metrics: {
      loginFrequency: 95,
      featureAdoption: 82,
      supportVolume: 'Low',
      csmEngagement: 90,
      vendorRisk: true,
      breachRisk: true,
      questionnaires: 22,
      riskAutomations: true,
    },
    news: [
      {
        id: 'n3',
        type: 'Successful QBR',
        title: 'Successful QBR',
        description: 'Q2 goals met. Engagement score up +12pts. Champion confirmed for renewal.',
        time: '3d ago',
        variant: 'success'
      },
      {
        id: 'n3b',
        type: 'Regulatory Change',
        title: 'MAS Cybersecurity Advisory',
        description: 'MAS issued new third-party risk guidelines for telcos. Creates urgency for Vendor Risk expansion.',
        time: '1w ago',
        variant: 'warning'
      }
    ]
  },
  {
    id: '3',
    name: 'Atlassian Ltd',
    shortName: 'AU',
    region: 'Australia',
    industry: 'Technology',
    healthScore: 84,
    grade: 'B',
    stage: 'Adopted',
    arr: 850000,
    nrr: 100,
    renewalDays: 122,
    renewalDate: '2026-09-01',
    adoptionDepth: 72,
    lastActivity: '1d ago',
    csm: 'ANZ Team',
    intervention: 'Invite to UpGuard Power User webinar. Feature adoption at 72% — push Risk Automations with Jira (native integration available). Atlassian using Jira internally makes this a zero-friction upsell.',
    metrics: {
      loginFrequency: 70,
      featureAdoption: 75,
      supportVolume: 'Moderate',
      csmEngagement: 80,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 11,
      riskAutomations: false,
    },
    news: [
      {
        id: 'n3c',
        type: 'Supply Chain Incident',
        title: 'Third-Party Incident',
        description: 'A key Atlassian SaaS vendor reported a data exposure incident affecting AU region.',
        time: '5d ago',
        variant: 'warning'
      }
    ]
  },
  {
    id: '4',
    name: 'Reliance Industries',
    shortName: 'IN',
    region: 'India',
    industry: 'Energy',
    healthScore: 68,
    grade: 'C',
    stage: 'Onboarding',
    arr: 560000,
    nrr: 0,
    renewalDays: 310,
    renewalDate: '2027-03-20',
    adoptionDepth: 45,
    lastActivity: '4h ago',
    csm: 'India Team',
    intervention: 'Week 4 onboarding check-in due. Assign dedicated implementation specialist. Target: 50 vendors monitored in 30 days. Feature adoption at 45% is below onboarding benchmark — escalate to Customer Success Engineer.',
    metrics: {
      loginFrequency: 50,
      featureAdoption: 30,
      supportVolume: 'Low',
      csmEngagement: 100,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 2,
      riskAutomations: false,
    },
    news: []
  },
  {
    id: '5',
    name: 'GCash / Mynt',
    shortName: 'PH',
    region: 'Philippines',
    industry: 'Fintech',
    healthScore: 95,
    grade: 'A',
    stage: 'Expanding',
    arr: 320000,
    nrr: 145,
    renewalDays: 205,
    renewalDate: '2026-11-25',
    adoptionDepth: 94,
    lastActivity: '12h ago',
    csm: 'SEA Team',
    intervention: 'Upsell: propose Trust Exchange module for their fintech partner ecosystem. NRR at 145% — highest in APAC portfolio. GCash expanding to rural banking means 200+ new third-party vendors to monitor.',
    metrics: {
      loginFrequency: 98,
      featureAdoption: 90,
      supportVolume: 'Low',
      csmEngagement: 95,
      vendorRisk: true,
      breachRisk: true,
      questionnaires: 34,
      riskAutomations: true,
    },
    news: [
      {
        id: 'n5a',
        type: 'Funding Round',
        title: 'Series D Closed',
        description: 'GCash raised $300M Series D. Expanded budget likely — ideal time for contract expansion discussion.',
        time: '2d ago',
        variant: 'primary'
      }
    ]
  },
  {
    id: '6',
    name: 'Grab Holdings',
    shortName: 'GR',
    region: 'Singapore',
    industry: 'Logistics',
    healthScore: 78,
    grade: 'B',
    stage: 'Adopted',
    arr: 950000,
    nrr: 105,
    renewalDays: 90,
    renewalDate: '2026-07-28',
    adoptionDepth: 65,
    lastActivity: '3h ago',
    csm: 'SEA Team',
    intervention: 'Activate Risk Automations — Grab uses Jira and Slack internally, both have native UpGuard integrations. Book a 30-min feature deep-dive to show automated vendor alerts in their workflow.',
    metrics: {
      loginFrequency: 80,
      featureAdoption: 60,
      supportVolume: 'Moderate',
      csmEngagement: 75,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 8,
      riskAutomations: false,
    },
    news: []
  },
  {
    id: '7',
    name: 'Samsung Electronics',
    shortName: 'KR',
    region: 'Korea',
    industry: 'Hardware',
    healthScore: 88,
    grade: 'A',
    stage: 'Renewal Due',
    arr: 4500000,
    nrr: 102,
    renewalDays: 15,
    renewalDate: '2026-05-15',
    adoptionDepth: 82,
    lastActivity: '1h ago',
    csm: 'East Asia Team',
    intervention: 'Renewal at risk of slipping despite A-grade health. Initiate renewal motion this week. Prepare multi-year contract proposal with User Risk module add-on. Do not let 15-day window close without signed order.',
    metrics: {
      loginFrequency: 90,
      featureAdoption: 85,
      supportVolume: 'Low',
      csmEngagement: 90,
      vendorRisk: true,
      breachRisk: true,
      questionnaires: 41,
      riskAutomations: true,
    },
    news: [
      {
        id: 'n7a',
        type: 'Renewal Alert',
        title: 'Renewal in 15 Days',
        description: '$4.5M ARR renewal approaching. Multi-year proposal not yet sent.',
        time: '1d ago',
        variant: 'warning'
      }
    ]
  },
  {
    id: '8',
    name: 'Tencent Games',
    shortName: 'CN',
    region: 'China',
    industry: 'Gaming',
    healthScore: 55,
    grade: 'D',
    stage: 'At Risk',
    arr: 1800000,
    nrr: 95,
    renewalDays: 30,
    renewalDate: '2026-05-30',
    adoptionDepth: 40,
    lastActivity: '6h ago',
    csm: 'China Team',
    intervention: 'Security alert active — send targeted breach report for CN gaming sector. Login frequency critical at 30%. Check if primary admin changed post-org restructure. Schedule intervention call this week before renewal in 30 days.',
    metrics: {
      loginFrequency: 30,
      featureAdoption: 50,
      supportVolume: 'High',
      csmEngagement: 40,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 5,
      riskAutomations: false,
    },
    news: [
      {
        id: 'n4',
        type: 'Security Alert',
        title: 'Security Vulnerability Detected',
        description: 'Multiple unpatched instances detected in regional CN nodes. Remediation overdue by 14 days.',
        time: '6h ago',
        variant: 'error'
      },
      {
        id: 'n4b',
        type: 'Renewal Alert',
        title: 'Renewal in 30 Days',
        description: '$1.8M contract renewal. Health score trending down — intervention required.',
        time: '2d ago',
        variant: 'warning'
      }
    ]
  },
  {
    id: '9',
    name: 'BHP Group',
    shortName: 'BH',
    region: 'Australia',
    industry: 'Mining',
    healthScore: 82,
    grade: 'B',
    stage: 'Expanding',
    arr: 720000,
    nrr: 110,
    renewalDays: 180,
    renewalDate: '2026-10-28',
    adoptionDepth: 68,
    lastActivity: '2d ago',
    csm: 'ANZ Team',
    intervention: 'APRA mining supply chain guidelines update creates Vendor Risk compliance urgency. Send sector-specific BHP use case. Propose expansion to cover refining and logistics partners — strong upsell angle.',
    metrics: {
      loginFrequency: 75,
      featureAdoption: 65,
      supportVolume: 'Low',
      csmEngagement: 85,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 14,
      riskAutomations: false,
    },
    news: [
      {
        id: 'n9a',
        type: 'Regulatory Change',
        title: 'APRA Supply Chain Update',
        description: 'New APRA guidelines require enhanced third-party oversight for critical infrastructure. BHP is in scope.',
        time: '4d ago',
        variant: 'warning'
      }
    ]
  },
  {
    id: '10',
    name: 'DBS Bank',
    shortName: 'DB',
    region: 'Singapore',
    industry: 'Finance',
    healthScore: 94,
    grade: 'A',
    stage: 'Adopted',
    arr: 2800000,
    nrr: 115,
    renewalDays: 160,
    renewalDate: '2026-10-08',
    adoptionDepth: 92,
    lastActivity: '4h ago',
    csm: 'APAC Team',
    intervention: 'Showcase account — nominate for UpGuard case study and reference customer program. Expansion: propose User Risk module for their 30,000-person workforce. DBS is highest-value account in APAC.',
    metrics: {
      loginFrequency: 96,
      featureAdoption: 90,
      supportVolume: 'Low',
      csmEngagement: 92,
      vendorRisk: true,
      breachRisk: true,
      questionnaires: 58,
      riskAutomations: true,
    },
    news: [
      {
        id: 'n10a',
        type: 'Successful QBR',
        title: 'QBR Completed — Score A',
        description: 'DBS security team confirmed UpGuard reduced vendor review time by 60%. Strong advocacy.',
        time: '1w ago',
        variant: 'success'
      }
    ]
  },
  {
    id: '11',
    name: 'Woolworths Group',
    shortName: 'WW',
    region: 'Australia',
    industry: 'Retail',
    healthScore: 75,
    grade: 'B',
    stage: 'Adopted',
    arr: 480000,
    nrr: 105,
    renewalDays: 45,
    renewalDate: '2026-06-15',
    adoptionDepth: 60,
    lastActivity: '1d ago',
    csm: 'ANZ Team',
    intervention: 'Renewal in 45 days — initiate conversation now. Feature adoption at 55% leaves upsell argument for questionnaire automation. Retail supply chain complexity = strong Vendor Risk expansion story.',
    metrics: {
      loginFrequency: 65,
      featureAdoption: 55,
      supportVolume: 'Moderate',
      csmEngagement: 75,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 9,
      riskAutomations: false,
    },
    news: []
  },
  {
    id: '12',
    name: 'Cathay Pacific',
    shortName: 'CP',
    region: 'Hong Kong',
    industry: 'Aviation',
    healthScore: 48,
    grade: 'D',
    stage: 'Churn Risk',
    arr: 650000,
    nrr: 88,
    renewalDays: 5,
    renewalDate: '2026-05-03',
    adoptionDepth: 35,
    lastActivity: '3h ago',
    csm: 'East Asia Team',
    intervention: 'CRITICAL: Renewal in 5 days. Escalate to VP Customer Success now. Login frequency at 20% — likely champion disengagement post-aviation restructure. Offer 30-day contract extension at no cost to recover relationship.',
    metrics: {
      loginFrequency: 20,
      featureAdoption: 40,
      supportVolume: 'High',
      csmEngagement: 50,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 2,
      riskAutomations: false,
    },
    news: [
      {
        id: 'n12a',
        type: 'Renewal Alert',
        title: 'CRITICAL: Renewal in 5 Days',
        description: '$650K ARR at risk. No renewal motion initiated. Champion unresponsive for 3 weeks.',
        time: '1h ago',
        variant: 'error'
      },
      {
        id: 'n12b',
        type: 'Executive Departure',
        title: 'CISO Role Vacant',
        description: 'Cathay CISO departed following restructure. Security budget decisions on hold.',
        time: '3w ago',
        variant: 'error'
      }
    ]
  },
  {
    id: '13',
    name: 'AirAsia',
    shortName: 'AA',
    region: 'Malaysia',
    industry: 'Aviation',
    healthScore: 62,
    grade: 'C',
    stage: 'Adopted',
    arr: 380000,
    nrr: 100,
    renewalDays: 140,
    renewalDate: '2026-09-15',
    adoptionDepth: 55,
    lastActivity: '12h ago',
    csm: 'SEA Team',
    intervention: 'Health trending flat. Book QBR — no touchpoints in 30+ days. Introduce automated threat digest for aviation supply chain. AirAsia expanding ground ops to PH/ID creates new Vendor Risk coverage need.',
    metrics: {
      loginFrequency: 55,
      featureAdoption: 45,
      supportVolume: 'Moderate',
      csmEngagement: 65,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 6,
      riskAutomations: false,
    },
    news: []
  },
  {
    id: '14',
    name: 'Petronas',
    shortName: 'PE',
    region: 'Malaysia',
    industry: 'Energy',
    healthScore: 85,
    grade: 'A',
    stage: 'Adopted',
    arr: 1500000,
    nrr: 108,
    renewalDays: 90,
    renewalDate: '2026-07-28',
    adoptionDepth: 78,
    lastActivity: '1d ago',
    csm: 'SEA Team',
    intervention: 'Energy sector facing increased supply chain scrutiny post-OPEC audit season. Propose Vendor Risk expansion to cover refining and downstream partners. Stable account — good candidate for multi-year renewal.',
    metrics: {
      loginFrequency: 85,
      featureAdoption: 70,
      supportVolume: 'Low',
      csmEngagement: 90,
      vendorRisk: true,
      breachRisk: true,
      questionnaires: 18,
      riskAutomations: false,
    },
    news: []
  },
  {
    id: '15',
    name: 'Commonwealth Bank',
    shortName: 'CB',
    region: 'Australia',
    industry: 'Finance',
    healthScore: 90,
    grade: 'A',
    stage: 'Expanding',
    arr: 3200000,
    nrr: 120,
    renewalDays: 30,
    renewalDate: '2026-05-30',
    adoptionDepth: 85,
    lastActivity: '2h ago',
    csm: 'ANZ Team',
    intervention: 'Top ANZ account. Renewal in 30 days — initiate multi-year contract conversation immediately. Propose APRA compliance reporting package as renewal upsell. Lock in before competitor outreach season (Q2 end).',
    metrics: {
      loginFrequency: 92,
      featureAdoption: 80,
      supportVolume: 'Low',
      csmEngagement: 95,
      vendorRisk: true,
      breachRisk: true,
      questionnaires: 47,
      riskAutomations: true,
    },
    news: [
      {
        id: 'n15a',
        type: 'Renewal Alert',
        title: 'Renewal in 30 Days',
        description: '$3.2M contract renewal. Multi-year proposal recommended — account is expanding.',
        time: '2d ago',
        variant: 'warning'
      },
      {
        id: 'n15b',
        type: 'Regulatory Change',
        title: 'APRA CPS 230 Compliance Deadline',
        description: 'New CPS 230 operational risk standard takes effect July 2026. Creates vendor risk urgency.',
        time: '1w ago',
        variant: 'primary'
      }
    ]
  },
  {
    id: '16',
    name: 'Rakuten',
    shortName: 'RK',
    region: 'Japan',
    industry: 'Ecommerce',
    healthScore: 72,
    grade: 'C',
    stage: 'Adopted',
    arr: 980000,
    nrr: 105,
    renewalDays: 75,
    renewalDate: '2026-07-15',
    adoptionDepth: 62,
    lastActivity: '5h ago',
    csm: 'Japan Team',
    intervention: 'Adoption plateau at 62%. Schedule feature training session focused on questionnaire automation. Rakuten expanding into PH/ID — offer APAC compliance briefing to align UpGuard with their regional growth strategy.',
    metrics: {
      loginFrequency: 70,
      featureAdoption: 55,
      supportVolume: 'Moderate',
      csmEngagement: 70,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 12,
      riskAutomations: false,
    },
    news: []
  },
  {
    id: '17',
    name: 'Standard Chartered',
    shortName: 'SC',
    region: 'Singapore',
    industry: 'Finance',
    healthScore: 87,
    grade: 'A',
    stage: 'Adopted',
    arr: 5500000,
    nrr: 103,
    renewalDays: 120,
    renewalDate: '2026-08-28',
    adoptionDepth: 80,
    lastActivity: '1h ago',
    csm: 'Global Team',
    intervention: 'Largest APAC account. Propose Trust Exchange for correspondent banking network — StanChart operates across 50+ markets. High-value expansion play targeting $7M+ ARR. Align with their global CISO for exec sponsorship.',
    metrics: {
      loginFrequency: 88,
      featureAdoption: 75,
      supportVolume: 'Low',
      csmEngagement: 85,
      vendorRisk: true,
      breachRisk: true,
      questionnaires: 63,
      riskAutomations: true,
    },
    news: [
      {
        id: 'n17a',
        type: 'CISO Hire',
        title: 'New Global CISO Appointed',
        description: 'StanChart appointed new Group CISO from Barclays. Relationship reset opportunity — schedule intro call.',
        time: '1w ago',
        variant: 'primary'
      }
    ]
  },
  {
    id: '18',
    name: 'BYD Auto',
    shortName: 'BY',
    region: 'China',
    industry: 'Manufacturing',
    healthScore: 65,
    grade: 'C',
    stage: 'Expanding',
    arr: 1100000,
    nrr: 125,
    renewalDays: 280,
    renewalDate: '2027-02-15',
    adoptionDepth: 50,
    lastActivity: '1d ago',
    csm: 'China Team',
    intervention: 'Expanding NRR but shallow adoption — risk of expansion without depth. Book product adoption audit. EV supply chain complexity (300+ tier-2 suppliers) is perfect Vendor Risk use case. Push questionnaire automation for supplier onboarding.',
    metrics: {
      loginFrequency: 60,
      featureAdoption: 40,
      supportVolume: 'Moderate',
      csmEngagement: 80,
      vendorRisk: true,
      breachRisk: false,
      questionnaires: 7,
      riskAutomations: false,
    },
    news: []
  }
];
